### ISSUE TITLE
ValidationError due to missing stillPath in episode data

### ISSUE THREAD

**Issue by DarkUser089** [Velocidensity/trakt-to-serializd#2]
I encountered a ValidationError while using trakt_to_serializd migrate. It appears that the issue is related to missing or None values for the stillPath field in episode data, which causes the migration to fail.

Here is the error output:

`pydantic_core._pydantic_core.ValidationError: 5 validation errors for SeasonResponse
episodes.0.stillPath
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
episodes.1.stillPath
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
episodes.2.stillPath
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
episodes.3.stillPath
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
episodes.4.stillPath
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
`

It seems that Serializd's API is returning None values for stillPath, but the Pydantic model expects a valid string.

Steps to Reproduce:

Run trakt_to_serializd migrate.
Wait for the migration process to start.
The error occurs during the migration of episodes with missing stillPath fields.

Environment:

Python version: 3.12.4
Operating System: Windows 11 (64-bit)
trakt-to-serializd version: [latest as of now]

**Comment by Velocidensity** [comment]
Thank you for the report. Fixed in https://github.com/Velocidensity/serializd-py/commit/3e436ddfa5d89b15415f1f82313ee1c92c8bb775.
